### ISSUE TITLE
Scrollbar on chrome

### ISSUE THREAD

**Issue by Mrkhagol** [matthias-schuetz/CustomScrollbar#2]
Chrome's latest version doesn't seem to support customscrollbar. Version 62.0.3202.62 
Meaning the scrollbar is getting customized but when the page is scolled, the scrollbar doesn't move and stays in one fixed place at top of the page.

![image](https://user-images.githubusercontent.com/5914348/31954879-c1571a30-b8b4-11e7-8ccc-9d3e6772145f.png)

![image](https://user-images.githubusercontent.com/5914348/31954895-cb9e44f0-b8b4-11e7-82db-7396285d4e55.png)

**Comment by matthias-schuetz** [comment]
Thank you a lot for your attention! I was busy in the last time and wouldn't have noticed it.
I fixed the issue and it works again in the latest Chrome.
Thanks again for the hint.
